### ISSUE TITLE
Phaser.WEBGL is shaky, CANVAS is fine

### ISSUE THREAD

**Issue by stahlmanDesign** [nkholski/phaser3-es6-webpack#12]
When using config.type: Phaser.WEBGL the background shakes. Using Phaser.CANVAS does not.

![shaky-smooth](https://user-images.githubusercontent.com/972804/37246623-e70fe64e-247a-11e8-8abd-95a4476cfd05.gif)

**Comment by nkholski** [comment]
Wierd. Do you get this in a local build or the hosted build (http://metroid.niklasberg.se/phaser3platformer/)?

**Comment by stahlmanDesign** [comment]
Only locally. I checked the hosted build in the latest versions of Chrome, FF and Safari and it doesn't shake. But when I `npm run dev` it shakes in all browsers locally.

**Comment by nkholski** [comment]
I'm thinking it's probably an issue with Phaser. Which version do you use?

**Comment by stahlmanDesign** [comment]
Looks like it is a problem with Phaser 3.1. In installed 3.2 and no more shake

**Comment by nkholski** [comment]
Ok! Thanks for bringing it up.
