### ISSUE TITLE
Mario can double-jump

### ISSUE THREAD

**Issue by ampled** [nkholski/phaser3-es6-webpack#16]
This is probably "out of scope" for the purpose of this project, but I just thought I'd make a quick note of it.

If you double-tap the jump button, Mario will get a tiny second jump in the middle of his initial jump.

I've tried fixing it but I'm not 100% sure about the logic around the jump-timer outside of enforcing how long you're allowed to hold the jump-button for upward momentum.

On a side-note, thanks for this lovely repo, it's certainly jump-started my grasp on phaser 😄

**Comment by nkholski** [comment]
Thanks! Double-jump is gone now. Happy to hear it's appreciated! :-)
