### ISSUE TITLE
mario/bendSuper

### ISSUE THREAD

**Issue by blachawk** [nkholski/phaser3-es6-webpack#19]
What does it typically mean when I recieved a warning in Google Chrome console that states the following as the game loads into my browser?

> phaser.js:28424 Texture.frame missing: mario/bendSuper

I'm recieving that message right now and not sure how to resolve it...

**Comment by nkholski** [comment]
Sorry. I seem to have left out that image when I went from a spritesheet to a spriteatlas. I'll fix it when I get time. If you update the spriteatlas I'd be happy to merge it.

**Comment by nkholski** [comment]
Fixed by @sebudde. Thanks!
