### ISSUE TITLE
npm install issues

### ISSUE THREAD

**Issue by richymel** [nkholski/phaser3-es6-webpack#3]
[npm log](https://dl.dropbox.com/s/oyzc0hbjjc5asnp/2017-08-31T04_30_13_561Z-debug.log)

**Comment by nkholski** [comment]
That's wierd. I'll look into it when I update for the first beta.

**Comment by richymel** [comment]
Hi there Niklas!
First I want to apologize for the inconvenience. I just realized that I had installed node-v6.11.1-x64.msi for windows which comes along with an adequate version of npm (I did not know this), so I went and installed the latest version of npm which caused some incompatibilities. I reinstalled nodejs to version v6.11.2, this comes with npm 3.10.10. Then, I npm installed your repo, and everything looks good now. Perhaps if you could kindly indicate what would be the next steps to start working with phaser and your repo (I am new to phaser (I undestand it is a complete game framework...) , I am evaluating graphic engines such as gsap (greensock), velocity, and react-game-kit for a learning game project I need to build with ReactJs. Thanks!

**Comment by nkholski** [comment]
I would advice you to use Phaser 2. Phaser 3 is pretty far from complete and is undocumented. Phaser 2 is however is well documented and has a great helpful community. Search for react in the forums and I bet you find something.
