### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by kfern** [nkholski/phaser3-es6-webpack#5]
Game works fine, but npm test list 88 problems (88 errors, 0 warnings)

**Comment by nkholski** [comment]
It's me not following the styling rules set by eslint. I might setup .editorconfig but it's no priority since this are not real errors, just for readability. It's mostly missing spaces.

However, I fixed that Phaser was undefined.

**Comment by kfern** [comment]
From https://phaser.io/phaser3/contributing

5. ESLint

There is an ESLint configuration and an Editor Configuration in the v3 folder. Please adhere to them! Although not enforced in the build process yet, I will be adding that at a later point. There are lots of tools you can install so your editor of choice will check the ESLint config during development.
